# Generated by Django 4.1.7 on 2023-03-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='short_description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
