# Generated by Django 4.1.7 on 2023-03-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0002_topic_image_topic_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(default='', upload_to='images/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
