# Generated by Django 4.1.7 on 2023-04-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0003_newspaper_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspaper',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
